openapi: 3.0.2
info:
  title: Ticket
  version: 1.0.0
  description: A Ticket system
  contact:
    name: Tom Salmon
    email: tom@tomsalmon.net
servers:
  - url: https://localhost:3001
paths:
  /v1/auth/user:
    get:
      description: Retrieves the logged in user.
      operationId: getUser
      responses:
        "200":
          description: User
          content:
            application/json:
              schema:
                type: object
                required:
                  - user
                properties:
                  user:
                    $ref: "#/components/schemas/User"
components:
  schemas:
    User:
      type: object
      required:
        - id
        - createdAt
        - updatedAt
        - deletedAt
        - firstName
        - lastName
      properties:
        id:
          description: ID
          x-go-type: uuid.UUID
          x-go-type-import:
            path: github.com/google/uuid
        createdAt:
          type: string
          format: date
        updatedAt:
          type: string
          format: date
        deletedAt:
          type: string
          format: date
          nullable: true
        firstName:
          description: User's given name
          type: string
        lastName:
          description: User's family name
          type: string
