// Code generated by templ@v0.2.334 DO NOT EDIT.

package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func input(params inputParams) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		templBuffer, templIsBuffer := w.(*bytes.Buffer)
		if !templIsBuffer {
			templBuffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templBuffer)
		}
		ctx = templ.InitializeContext(ctx)
		var_1 := templ.GetChildren(ctx)
		if var_1 == nil {
			var_1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, err = templBuffer.WriteString("<div>")
		if err != nil {
			return err
		}
		if params.Label != "" {
			_, err = templBuffer.WriteString("<label for=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(params.ID))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\" class=\"block mb-2 text-sm font-medium text-slate-900 dark:text-slate-50\">")
			if err != nil {
				return err
			}
			var var_2 string = params.Label
			_, err = templBuffer.WriteString(templ.EscapeString(var_2))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("</label>")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("<input id=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(params.ID))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" name=\"")
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString(templ.EscapeString(params.ID))
		if err != nil {
			return err
		}
		_, err = templBuffer.WriteString("\" class=\"\n        block w-full p-2.5 border text-sm rounded-lg\n        bg-slate-50 dark:bg-slate-700\n        border-slate-300 dark:border-slate-600\n        text-slate-900 dark:text-slate-50\n        focus:ring-blue-500 dark:focus:ring-slate-600\n        focus:border-blue-500 dark:focus:border-slate-600\n        dark:placeholder-slate-400\"")
		if err != nil {
			return err
		}
		if params.Type != "" {
			_, err = templBuffer.WriteString(" type=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(params.Type))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"")
			if err != nil {
				return err
			}
		}
		if params.Placeholder != "" {
			_, err = templBuffer.WriteString(" placeholder=\"")
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString(templ.EscapeString(params.Placeholder))
			if err != nil {
				return err
			}
			_, err = templBuffer.WriteString("\"")
			if err != nil {
				return err
			}
		}
		if params.Required {
			_, err = templBuffer.WriteString(" required")
			if err != nil {
				return err
			}
		}
		_, err = templBuffer.WriteString("></div>")
		if err != nil {
			return err
		}
		if !templIsBuffer {
			_, err = templBuffer.WriteTo(w)
		}
		return err
	})
}
